#!/usr/bin/env bash
# configure nginx to redirect 

# backup original default config
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# add a location block in default server block
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    
    location = /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}" | sudo tee /etc/nginx/sites-available/redirect_me

# remove the default symlink
sudo rm /etc/nginx/sites-enabled/default

# enablle the new sserver block
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/


# test the config
sudo nginx -t

# if config is successful reload nginx
if [ $? -eq 0 ]
then
    sudo service nginx restart
else
    echo "failed to reload nginx"
fi
