#!/usr/bin/env bash
# configure nginx to redirect 

# install nginx
sudo apt-get update -y -qq && sudoo apt-get install nginx -y

# start nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'

# set the user ownership to website files
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# create new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debial.html

# rediret
sudo sed -i '24i\    rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# restart 
sudo service nginx restart

echo -e "\n done"
