#!/usr/bin/env bash
# This script configures Nginx to display a custom 404 page

# Check if nginx is installed
if ! command -v nginx &> /dev/null
then
    echo "nginx could not be found. Please install nginx first."
    exit
fi

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# Create a new server block configuration file
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    
    error_page 404 /custom_404.html;
    location = /custom_404.html {
        root /var/www/html;
        internal;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}" | sudo tee /etc/nginx/sites-available/custom_404

# Remove the default symlink in sites-enabled
sudo rm /etc/nginx/sites-enabled/default

# Enable the new server block
sudo ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Test the config
sudo nginx -t

# if config is successful reload nginx
if [ $? -eq 0 ]
then
    sudo service nginx restart
else
    echo "Failed to reload nginx. Please check your configuration."
fi

