#!/usr/bin/env bash
# this script configures nginx to run on port 80

# remoce the default nginx config file
rm /etc/nginx/sites=enabled/default
# configures nginx to listen on port 80 for all active ipv4 ips
ls -s /etc/nginx/sites=available/default /etc/nginx/sites=enabled/default# restart nginx
service nginx restart
