#!/usr/bin/env bash
# config nginx to listen on port 80

# createt a symbolic link between the nginx config file
# and the enabled sites directory
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
